### ISSUE TITLE
139/140 conjurations

### ISSUE THREAD

**Issue by HQv2** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#5]
Hello. I have collected everything in the game yet it says I have only 139/140 conjurations. There are many reports of this being a bug which prevents you from getting the 'Collectors Edition' achievement. Any idea how to fix this? Thank you!

![Screenshot_12](https://user-images.githubusercontent.com/42633588/221330465-97a34528-cf7c-45ac-8b15-8a0099af9604.jpg)

![Screenshot_13](https://user-images.githubusercontent.com/42633588/221330673-a3f37feb-b364-4476-993e-d920bc6768e1.jpg)

**Comment by Malin001** [comment]
Yeah looking at your screenshots, there's defintely a mistake somewhere in my code. Unfortunately, after looking through it I can't spot where it is. If you send me your save file (like in [this](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/issues/2) issue) I can try to find where it is for you, and fix Legilimens in the process.

**Comment by tarrouye** [comment]
> Yeah looking at your screenshots, there's defintely a mistake somewhere in my code. Unfortunately, after looking through it I can't spot where it is. If you send me your save file (like in [this](https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/issues/2) issue) I can try to find where it is for you, and fix Legilimens in the process.

Hi @Malin001 ! I have a similar issue as the OP (139/140 conjurations, but Legilimens only shows me 3 missing field guide pages) 

Here is my save file: https://file.io/j5EoM2zxRKqe

Here are the only things Legilimens shows as missing: 

![image](https://user-images.githubusercontent.com/5017270/221522622-ba71c33d-a858-400d-91e1-da59479017d0.png)

And here is the game: 
![image](https://user-images.githubusercontent.com/5017270/221523598-c232fe94-fad4-4a6b-9194-0de03925584c.png)
![image](https://user-images.githubusercontent.com/5017270/221523756-b1c5f755-ed06-4ff9-b7b0-4c86289aee62.png)


(The moth painting field guide page #24 is bugged for me, the moth doesn't spawn. So, I suspect it's likely that the conjuration is also bugged. But, anyways, maybe it can be helpful for you.)

**Comment by Malin001** [comment]
Thanks for sending your save! I admit that I also suspect a potential bug in the game, but this save should go a long way to helping me figure out whether or not that's actually the case. Either way I'll let you know once I discover the problem.

**Comment by HQv2** [comment]
There was definitely a bug in the game where a butterfly chest sometimes didn't count towards the conjurations. I believe it's been fixed but the people who already collected that chest are screwed until they possibly release a patch. You can fix it by using this save editor and clicking the "Save the Butterflies" button to make the mission available again. Once you complete that mission, you will get the last conjuration as well as the achievement if you already unlocked everything else.

https://hogwarts-legacy-save-editor.vercel.app/

**Comment by tarrouye** [comment]
@Malin001 yeah I also suspect a bug in the game, but figured the save could help you rule out a bug on your side :) 

@HQv2 Thanks for the tip. To be honest I imagine there are multiple triggers for the bug, of which missing the butterfly chest from the quest is one of them. I'm fairly certain that I did that quest properly. But, for science, I'll make a copy of my save and try resetting that quest when I have some more time.

**Comment by Malin001** [comment]
I created a save where I intentionally got the butterfly chest bug, and I can confirm that Legilimens simply detects it as missing Butterfly Chest 1, which means that this is probably [a completely separate bug](https://hogwartslegacy.bugs.wbgames.com/bug/HL-3868). I've been sent a handful of saves with the 139/140 problem and after thoroughly testing them, I have _absolutely no idea_ where the last conjuration is.

I know that there are exactly 96 exploration conjurations. 15 are butterflies, 12 are vivariums, and the remaining 69 are collection chests that show up on the map and would therefore be trivially easy to find. On each save I was given, every collection chest on the map was finished, and I manually checked every butterfly and vivarium chest. I also know that Legilimens detects exactly 15 unique butterfly chests, 12 unique vivarium chests, and 69 unique collectible conjuration chests, so if it was missing a chest, that would mean there are more chests than there are collectibles. And so it makes _no sense_ that any of these saves are missing a conjuration.

Some people have reportedly claimed that they received a duplicate conjuration from a chest, which I suppose is a plausible enough explanation. I haven't seen any indications in the save files that I've looked at that the character might have two copies of a single conjuration, so the only way for me to test it would be to keep resetting my save and opening chests until I got a duplicate, which is way too much time to spend on something that I don't even know is possible.

I'll keep looking into it when I have time, but for now I'm declaring that this is a bug in Hogwarts Legacy, not Legilimens, at least until I'm shown evidence otherwise.
